### ISSUE TITLE
Can't remove "the thing" that's attached to my token

### ISSUE THREAD

**Issue by dmrickey** [KayelGee/token-attacher#66] opened 2022-01-15 08:21 UTC
Apparently there's something attached to my token--I don't see anything. Trying to break all attachments in the attacher menu doesn't do anything. I was able to fix it by deleting the token and putting a new one in the scene, but hopefully I took enough screen captures that it's useful for preventing it from breaking again (at least when it's attempting to read, I don't know how the bad data go there to begin with).

![image](https://user-images.githubusercontent.com/3664822/149596213-ade3009f-5895-4f98-851d-fbe6616e8b3f.png)
![image](https://user-images.githubusercontent.com/3664822/149614761-50f55c2a-099c-44de-b9c0-9263a502b106.png)
![image](https://user-images.githubusercontent.com/3664822/149614821-8b2109d9-f7bd-481a-9a1d-58b87c164e75.png)
![image](https://user-images.githubusercontent.com/3664822/149614831-cd1b2cf2-8454-4fa8-b10f-c990a99d3cee.png)

```
token-attacher.js:575 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'data')
[Detected 2 packages: token-attacher, drag-ruler]
    at token-attacher.js:575
    at Array.map (<anonymous>)
    at Function._UpdateAttachedOfBase (token-attacher.js:575)
    at Function.UpdateAttachedOfToken (token-attacher.js:555)
    at token-attacher.js:215
    at Function._call (foundry.js:294)
    at Function.callAll (foundry.js:253)
    at ClientDatabaseBackend.callback (foundry.js:10254)
    at foundry.js:10224
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleUpdateEmbeddedDocuments (foundry.js:10224)
    at ClientDatabaseBackend._updateEmbeddedDocuments (foundry.js:10106)
    at async Function.updateDocuments (document.mjs:373)
    at async DragRulerRuler.animateEntities (foundry_imports.js:90)
    at async DragRulerRuler.moveEntities (foundry_imports.js:41)
```

**Comment by KayelGee** [comment] 2022-01-24 19:42
Looks like the template got somehow deleted.
There's been a bug in an older version of token attacher that didn't properly detach elements that were deleted. Maybe that is what caused it.

**Comment by dmrickey** [comment] 2022-01-26 19:40
Hm, I doubt it -- unless the data was attached to the actor instead of the token. I deleted the token at some point to try and fix it and it still happened again. But I don't remember if it happened immediately or sometime after the fact

**Comment by KayelGee** [comment] 2022-10-19 12:17
I fixed a lot of things in the past weeks. I noticed that some of the stuff was broken before v10. I think the issue you had here was also caused by one of those. I didn't test for this, but looking at your screenshots I'm pretty sure I had exactly this problem reproduced on my end. 
I'll close this issue, but if it crops up again feel free to post another issue.

**Closed by KayelGee** 2022-10-19 12:17 UTC
