### ISSUE TITLE
Using waypoints for token movement(this includes Drag Ruler) causes root token to teleport

### ISSUE THREAD

**Issue by Sravdar** [KayelGee/token-attacher#35] opened 2021-06-13 23:34 UTC
When both modules are active and something attached to token, root token moves in double speed and goes twice the way it should normally go (by cliping through walls etc) and then teleports back to place where it normally should be.

Weirdly if you press and hold "ALT" before you drop the token than it just moves in normal animaiton.

**Comment by iotech-fvtt** [comment] 2021-07-03 04:10
Confirmed. I'm having an issue with Drag Ruler and Token Attacher on 0.8.8 self hosted. Player or GM, example: Move any token from A to B distance X in direction Y= on drag release, token draws at B, then moves in direction Y for X distance, passing through walls and providing vision, then snaps back to B.

Confirmed normal operation with either Drag Ruler or Token Attacher disabled, but with both enabled, the above behavior is observed.

**Comment by KayelGee** [comment] 2021-07-03 14:20
I haven't played around with drag ruler yet but I'll check if this is fixable the next time I'm at the code

**Comment by KayelGee** [comment] 2021-09-03 09:47
So I looked into the issue and this is not caused by the Drag Ruler module. This already happens when you use the core foundry waypoints to move your token.
The reason this happens is because I update some value when the token get's moved and the animation system updates it's start position when any update happens, so it adjusts the animation which causes the teleportation. I'll probably report this as a core bug, because the animation shouldn't need to adjust itself, because I'm not updating any position data.

For now I'll leave this open. As a temporary solution you can deactivate token animation, if you don't want the movement to teleport through walls.

**Comment by KayelGee** [comment] 2021-09-03 11:50
Nevermind turns out it was a bug on my end because of a misunderstanding.
Will be fixed in the next update.

**Closed by KayelGee** 2021-09-03 11:50 UTC
Labels: bug

**Comment by Hydrologist** [comment] 2021-09-30 01:59
This bug is occurring again when version 4.2.0 of this module is used together with DnD5e Helpers version 3.0.2. It specifically occurs when the "Enable Combat Action Management" setting in DnD5e Helpers is set to anything other than Disabled. I'm running Foundry version 0.8.9 on a dedicated server.

Given that you've fixed this for other cases and this only happens when used with this particular setting, I imagine this interaction may be on DnD5e Helpers' side, but I thought I'd let you know in case you have the bandwidth to look at it.
