### ISSUE TITLE
Template gets detached from the token when drop on canvas

### ISSUE THREAD

**Issue by DarKDinDoN** [KayelGee/token-attacher#10] opened 2020-11-09 15:02 UTC
Hello

FVTT 0.7.6
5e 0.99

Sometimes (quite randomly), when the GM drops an actor on the canvas with a template attached to the prototype token, the template does not move with the token.
Couldn't reproduce a specific use case for this.

Might be because the template is initialized and therefore attached before the token is even properly created?

**Comment by KayelGee** [comment] 2020-11-09 22:09
If you can't reproduce a specific case then this might be because of the race condition highlighted in this issue in core foundry: https://gitlab.com/foundrynet/foundryvtt/-/issues/3455
I'll try to look at the template code anyways just in case I have made a mistake somewhere.

**Comment by KayelGee** [comment] 2021-02-05 12:31
I'll close this for now. If this should happen reqularly in 4.0 open a new issue as a lot of code has changed so there might be  a different behaviour now.

**Closed by KayelGee** 2021-02-05 12:31 UTC
