### ISSUE TITLE
attached token does not respond to double-click with D35E

### ISSUE THREAD

**Issue by wmve** [KayelGee/token-attacher#40] opened 2021-06-15 16:32 UTC
when i attack a pc/npc token to another token, i can no longer open the character sheet of the attached token by double clicking.  
this situation does have a workaround, of course (open sheet from actor list), so it's not urgent, but inconvenient.

**steps to reproduce:**
1. double click on token; observe character sheet; close character sheet
2. attach token to another token
3. double click on token
**expected behaviour:** character sheet will open
**actual behaviour:** character sheet does not open

three actors that i have reproduced this with:
[fvtt-Actors-dont-respond-to-dblclk.zip](https://github.com/KayelGee/token-attacher/files/6657200/fvtt-Actors-dont-respond-to-dblclk.zip)

i don't see much of note in the console log, except for these messages, which do not reproduce all the time.  only when i just open the console when i have the mouse hover over such a token
![image](https://user-images.githubusercontent.com/55966777/122090242-936c2b80-cdd5-11eb-8b5f-db4afccb4d71.png)

versions:
![image](https://user-images.githubusercontent.com/55966777/122088916-3b80f500-cdd4-11eb-8ded-670a71188df0.png)

**Comment by KayelGee** [comment] 2021-06-15 19:51
Just a heads up, this one is not expected behaviour. But I have trouble reproducing what you're describing. The character sheet is still opening with a double click after attaching to another token.

**Comment by KayelGee** [comment] 2021-06-15 20:03
I just noticed you're on foundry 0.8.6 while I've been testing on 0.8.7. Maybe that's why it behaves differently

**Comment by KayelGee** [comment] 2021-09-03 09:15
I couldn't reproduce it on my end, maybe it was fixed with an update to the system

**Closed by KayelGee** 2021-09-03 09:15 UTC
Labels: non-repro
