### ISSUE TITLE
More Aggressive Purge and/or Better Multilevel Tokens Purge Needed

### ISSUE THREAD

**Issue by tjlanza** [KayelGee/token-attacher#45] opened 2021-06-23 17:26 UTC
Foundry 0.8.7, TA 4.1.2, MLT 1.5.1

![image](https://user-images.githubusercontent.com/21128724/123139516-4f57d700-d424-11eb-9e68-688d38660b23.png)

With the understanding that MLT and TA are not completely compatible, there is a need for a more powerful tool to correct TA issues when conflicts arise. I had a token with a few attached tokens that did not get loaded properly despite TA saying it had (an issue issue I will post separately when I can reproduce it reliably). When I tried to move them, I got the above error message, and did as it says.

Unfortunately, it did not work. I deleted all the TA-configured tokens in the scene I was working with, but it didn't help. In my current world, I now get that message six to ten times (or more) any time I change scenes, alter a scene's properties, or refresh my browser.  The message occurs even with all scenes removed from the navigation bar and only a single non-MLT Obviously, the error goes away with MLT disabled.

I suspect there's an issue with cloned tokens, as the tokens were in an MLT cloning region. Unfortunately, I don't have the technical expertise to provide any specifics.

In my use case, MLT is the higher priority of the two modules - TA provides convenience, but MLT provides important functionality. I would like a more aggressive method of removing TA-related flags from any and all actors and token. At this point, a scorched earth nuclear option would be acceptable. I don't have a problem setting things up again, but this persistent error message makes TA effectively unusable. The only option available to me now appears to be disabling TA and never using it again.

**Comment by tjlanza** [comment] 2021-06-23 17:59
With TA disabled, a browser refresh is now giving:

![image](https://user-images.githubusercontent.com/21128724/123144964-4964f480-d42a-11eb-8a53-fca276d628c6.png)

![image](https://user-images.githubusercontent.com/21128724/123145497-e2940b00-d42a-11eb-81a3-6f175de7c378.png)

While it's likely caused by something MLT-related, as TA is disabled, I'm posting it here because TA is the genesis of the issue. I suspect it is the object that the "(TA)Delete missing Links" macro failed to clean up.

Note that I have created an issue on the MLT git and provided a link to this issue.

**Comment by KayelGee** [comment] 2021-06-23 18:58
I haven't done any testing related to this yet but I want to say that there's a foundry core bug in 0.8.7:
When deleting doors an exception will be thrown and only one door will seemingly be deleted. The rest will remain until a page refresh. The second error you posted may stem from that. You have to refresh after deleting a door or you'll see a lot of unexpected behaviour. 

I honestly don't intend to touch foundry 0.8.7 because this bug is really annoying to work with when you use prefabs.

**Comment by tjlanza** [comment] 2021-06-23 20:07
> I haven't done any testing related to this yet but I want to say that there's a foundry core bug in 0.8.7:
> When deleting doors an exception will be thrown and only one door will seemingly be deleted. The rest will remain until a page refresh. The second error you posted may stem from that. You have to refresh after deleting a door or you'll see a lot of unexpected behaviour.
> 
> I honestly don't intend to touch foundry 0.8.7 because this bug is really annoying to work with when you use prefabs.

I only use TA for token-token attachments; there are no doors involved.

**Comment by KayelGee** [comment] 2021-06-23 21:02
That's good to know. 
Here's a macro that you can use to remove all token attacher related data in the scene:

```
(async () =>{		
	const base_layer = 	canvas.getLayerByEmbeddedName("Token");
	const moduleName = 'token-attacher';
	let updates = {};
	const pushUpdate = (key, update, updateObj) => {
		if(!updateObj.hasOwnProperty(key)) updateObj[key] = [];
		const dupIndex = updateObj[key].findIndex(item => update._id=== item._id);
		if(dupIndex === -1) updateObj[key].push(update);
	};
	for (const type of ["AmbientLight", "AmbientSound", "Drawing", "MeasuredTemplate", "Note", "Tile", "Token", "Wall"]) {
		const layer = canvas.getLayerByEmbeddedName(type);
		const deleteLinks = (layer) => {
				for (let i = 0; i < layer.placeables.length; i++) {
					const element = layer.placeables[i];
					if(getProperty(element, `data.flags.${moduleName}`)) pushUpdate(type, {_id:element.data._id, [`flags.-=${moduleName}`]:null}, updates);
				}
			}
		deleteLinks(layer);
		if(type === "Tile"){
			deleteLinks(canvas.foreground);
		}
	}
	//Fire updates
	for (const key in updates){
		if (updates.hasOwnProperty(key)) {
			await canvas.scene.updateEmbeddedDocuments(key, updates[key], {[moduleName]:{}});
		}
	}
})();
```

See if that fixes your issue.

**Comment by tjlanza** [comment] 2021-06-24 00:17
That seems to have done the job. In fact, tokens appeared that were not present before running it - tokens that correspond to the one I was trying to work with when things went all squirrelly. I'm guessing they were MLT's cloned tokens or something that was linked to them somehow. Either way, when I deleted them, the other message went away as well. Thanks.

**Comment by KayelGee** [comment] 2021-06-24 07:34
I'll add the purge function to the gm menu and also the purge macro to the example macros(so one can purge even without token attacher being enabled) in the next update.

If you find a way to recreate the issue you were having, open a new issue for that and hopefully we can work out a fix.

**Comment by KayelGee** [comment] 2021-09-03 09:10
Purge macro and button in gm menu will be in next update.

**Closed by KayelGee** 2021-09-03 09:10 UTC
