### ISSUE TITLE
Erratic behaviour when used with About Face activated

### ISSUE THREAD

**Issue by RakeshP94** [KayelGee/token-attacher#14] opened 2020-12-23 06:57 UTC
When a token with the About Face module activated has something attached to it, the attached item behaves erratically when the token is moved.

Token Attacher with About Face (used Baileywiki's Cart asset):
![With About Face](https://user-images.githubusercontent.com/38881694/102968579-1e045a00-451a-11eb-97a8-1b85bac974e2.gif)

**Comment by RakeshP94** [comment] 2020-12-23 10:27
A temporary stopgap measure is to lock the rotation of the token which has things attached to it.

**Comment by KayelGee** [comment] 2020-12-24 02:12
I'll have to check what the cause is

**Comment by KayelGee** [comment] 2021-02-05 12:27
Fixed in 4.0

**Closed by KayelGee** 2021-02-05 12:27 UTC
